{
  "contact_name": "Toby Flenderson",
  "position_name": "The Ryan of the Office",
  "job_listing_source": "Scranton Times",
  "company_name": "Barry Bluestone Paper Company",
  "company_add_1": "1135 Tremont St",
  "company_add_2": "360RP",
  "company_csz": "Boston, MA 02115",
  "to_recruiter": False
}
